name: Auto Git Pull on Server

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Connect to Server and Pull Latest Code
        run: |
          find / -type d -name "visualize_self" 2>/dev/null | grep visualize_self || true
          echo "Git pull completed successfully!"
