name: Auto Git Pull on Server

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Check Runner User
        run: |
          whoami
          pwd
          ls -la
