name: Auto Git Pull on Server

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Runner User
        run: |
          cd /home
          ls -al
